docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**
          - playwright.config.*

styles:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.css"
